version: '3'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      context: ./api
      dockerfile: ./build/package/Dockerfile.dev
    command: reflex -r '(\.go|go\.mod)' -s go run cmd/http/main.go
    environment:
      DATABASE_DSN: host=db user=postgres password=postgres dbname=todo_dev port=5432 sslmode=disable
    working_dir: /go/src/api
    volumes:
      - ./api:/go/src/api
      - ./go-pkg-data:/go/pkg
    ports:
      - 1323:1323
    depends_on:
      - db
  spa:
    image: node:14.15.1-alpine3.12
    command: yarn start
    env_file:
      - .env.local
    working_dir: /work
    volumes:
      - ./spa:/work
      - ./yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - 3000:3000