version: '3'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
  api:
    image: golang:1.15.2-alpine3.12
    command: go run server.go
    working_dir: /go/src/api
    volumes:
      - ./api:/go/src/api
      - ./go-pkg-data:/go/pkg
    depends_on:
      - db